# Generated by Django 2.2.5 on 2019-09-30 22:28

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(username="testuser", email="wangjess@umich.edu", password="password").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190930_2227'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]